"""SymmetricRealAmplitudes ansatz with per‑layer parameter sharing.

The ansatz mirrors the classic RealAmplitudes construction but enforces that
every rotation gate in a given layer shares the *same* rotation angle.
This introduces a global symmetry across qubits, reduces the number of free
parameters, and can improve trainability for problems where such symmetry is
physically relevant.
"""

from __future__ import annotations

from typing import Callable, List, Sequence, Tuple

from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector


def _resolve_entanglement(
    num_qubits: int,
    entanglement: str | Sequence[Tuple[int, int]] | Callable[[int], Sequence[Tuple[int, int]]],
) -> List[Tuple[int, int]]:
    """Return a list of qubit pairs for two‑qubit entanglers.

    Parameters
    ----------
    num_qubits : int
        Number of qubits in the circuit.
    entanglement : str | Sequence[Tuple[int, int]] | Callable[[int], Sequence[Tuple[int, int]]]
        Either a keyword string ('full', 'linear', 'circular'), a custom list of
        index tuples, or a callable that returns such a list.

    Returns
    -------
    List[Tuple[int, int]]
        Validated list of distinct qubit pairs.

    Raises
    ------
    ValueError
        If an unsupported string is supplied or a pair contains an out‑of‑range
        qubit index.
    """
    if isinstance(entanglement, str):
        if entanglement == "full":
            return [(i, j) for i in range(num_qubits) for j in range(i + 1, num_qubits)]
        if entanglement == "linear":
            return [(i, i + 1) for i in range(num_qubits - 1)]
        if entanglement == "circular":
            pairs = [(i, i + 1) for i in range(num_qubits - 1)]
            if num_qubits > 2:
                pairs.append((num_qubits - 1, 0))
            return pairs
        raise ValueError(f"Unsupported entanglement keyword: {entanglement!r}")

    if callable(entanglement):
        pairs = list(entanglement(num_qubits))
        return [(int(i), int(j)) for (i, j) in pairs]

    pairs = [(int(i), int(j)) for (i, j) in entanglement]  # type: ignore[arg-type]
    for (i, j) in pairs:
        if i == j:
            raise ValueError("Entanglement pairs must connect distinct qubits.")
        if not (0 <= i < num_qubits and 0 <= j < num_qubits):
            raise ValueError(f"Entanglement pair {(i, j)} out of range for n={num_qubits}.")
    return pairs


def symmetric_real_amplitudes(
    num_qubits: int,
    reps: int = 1,
    entanglement: str | Sequence[Tuple[int, int]] | Callable[[int], Sequence[Tuple[int, int]]] = "full",
    skip_final_rotation_layer: bool = False,
    insert_barriers: bool = False,
    parameter_prefix: str = "theta",
    name: str | None = None,
) -> QuantumCircuit:
    """Build a parameter‑shared RealAmplitudes circuit.

    The circuit consists of ``reps`` layers of global RY rotations (one
    shared parameter per layer) followed by entangling CX gates.  An optional
    final rotation layer may be omitted.

    Parameters
    ----------
    num_qubits : int
        Number of qubits.
    reps : int, default 1
        Number of entanglement + rotation blocks.
    entanglement : str | Sequence[Tuple[int, int]] | Callable[[int], Sequence[Tuple[int, int]]], default "full"
        Specification of the two‑qubit entanglement pattern.
    skip_final_rotation_layer : bool, default False
        If ``True`` the final rotation layer after the last entanglement
        block is omitted.
    insert_barriers : bool, default False
        If ``True`` insert barriers between layers for easier circuit
        inspection.
    parameter_prefix : str, default "theta"
        Prefix for the autogenerated parameter names.
    name : str | None, default None
        Optional name for the resulting circuit.

    Returns
    -------
    QuantumCircuit
        The constructed ansatz.

    Raises
    ------
    ValueError
        If ``num_qubits`` is less than 1 or ``reps`` is negative.
    """
    if num_qubits < 1:
        raise ValueError("num_qubits must be >= 1.")
    if reps < 0:
        raise ValueError("reps must be non‑negative.")

    n = int(num_qubits)
    qc = QuantumCircuit(n, name=name or "SymmetricRealAmplitudes")

    num_rot_layers = reps if skip_final_rotation_layer else reps + 1
    params = ParameterVector(parameter_prefix, num_rot_layers)

    def _rotation_layer(layer_idx: int) -> None:
        """Apply a shared RY rotation to all qubits for the given layer."""
        param = params[layer_idx]
        for q in range(n):
            qc.ry(param, q)

    ent_pairs = _resolve_entanglement(n, entanglement)

    for r in range(reps):
        _rotation_layer(r)
        if insert_barriers:
            qc.barrier()
        for (i, j) in ent_pairs:
            qc.cx(i, j)
        if insert_barriers:
            qc.barrier()

    if not skip_final_rotation_layer:
        _rotation_layer(reps)

    qc.input_params = params  # type: ignore[attr-defined]
    qc.num_rot_layers = num_rot_layers  # type: ignore[attr-defined]
    return qc


class SymmetricRealAmplitudes(QuantumCircuit):
    """Convenience wrapper that behaves like Qiskit's ``QuantumCircuit``.

    Parameters
    ----------
    num_qubits : int
        Number of qubits.
    reps : int, default 1
        Number of entanglement + rotation blocks.
    entanglement : str | Sequence[Tuple[int, int]] | Callable[[int], Sequence[Tuple[int, int]]], default "full"
        Specification of the two‑qubit entanglement pattern.
    skip_final_rotation_layer : bool, default False
        If ``True`` the final rotation layer after the last entanglement
        block is omitted.
    insert_barriers : bool, default False
        If ``True`` insert barriers between layers for easier circuit
        inspection.
    parameter_prefix : str, default "theta"
        Prefix for the autogenerated parameter names.
    name : str, default "SymmetricRealAmplitudes"
        Optional name for the circuit.
    """

    def __init__(
        self,
        num_qubits: int,
        reps: int = 1,
        entanglement: str | Sequence[Tuple[int, int]] | Callable[[int], Sequence[Tuple[int, int]]] = "full",
        skip_final_rotation_layer: bool = False,
        insert_barriers: bool = False,
        parameter_prefix: str = "theta",
        name: str = "SymmetricRealAmplitudes",
    ) -> None:
        built = symmetric_real_amplitudes(
            num_qubits=num_qubits,
            reps=reps,
            entanglement=entanglement,
            skip_final_rotation_layer=skip_final_rotation_layer,
            insert_barriers=insert_barriers,
            parameter_prefix=parameter_prefix,
            name=name,
        )
        super().__init__(built.num_qubits, name=name)
        self.compose(built, inplace=True)

        self.input_params = built.input_params  # type: ignore[attr-defined]
        self.num_rot_layers = built.num_rot_layers  # type: ignore[attr-defined]


__all__ = ["SymmetricRealAmplitudes", "symmetric_real_amplitudes"]
