"""Unified hybrid classifier with a quantum expectation head.

This module implements a version of `UnifiedHybridClassifier` that
replaces the classical head with a variational quantum circuit.
The circuit is generated by `build_classifier_circuit` (from
reference pair 3) and executed on a Qiskit Aer simulator.  A
custom autograd function implements the parameter‑shift rule for
back‑propagation through the quantum circuit.
"""

from __future__ import annotations

import math
from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import qiskit
from qiskit import QuantumCircuit, execute, transpile, assemble
from qiskit.quantum_info import SparsePauliOp

# ------------------------------------------------------------------
# 1.  Quantum circuit factory (from QuantumClassifierModel.py)
# ------------------------------------------------------------------
def build_classifier_circuit(num_qubits: int, depth: int):
    """Construct a simple layered ansatz with explicit encoding and variational parameters."""
    encoding = qiskit.circuit.ParameterVector("x", num_qubits)
    weights = qiskit.circuit.ParameterVector("theta", num_qubits * depth)

    circuit = QuantumCircuit(num_qubits)
    for param, qubit in zip(encoding, range(num_qubits)):
        circuit.rx(param, qubit)

    index = 0
    for _ in range(depth):
        for qubit in range(num_qubits):
            circuit.ry(weights[index], qubit)
            index += 1
        for qubit in range(num_qubits - 1):
            circuit.cz(qubit, qubit + 1)

    observables = [SparsePauliOp("I" * i + "Z" + "I" * (num_qubits - i - 1)) for i in range(num_qubits)]
    return circuit, list(encoding), list(weights), observables

# ------------------------------------------------------------------
# 2.  Custom autograd function for quantum expectation
# ------------------------------------------------------------------
class QuantumExpectationFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, inputs: torch.Tensor, circuit: QuantumCircuit, weights: list, shots: int, backend):
        # Flatten inputs to a 1‑D list of parameters
        param_list = inputs.detach().cpu().numpy().flatten().tolist()
        param_bind = [{weights[i]: param_list[i] for i in range(len(weights))}]
        compiled = transpile(circuit, backend)
        qobj = assemble(compiled, shots=shots, parameter_binds=param_bind)
        job = backend.run(qobj)
        result = job.result()
        counts = result.get_counts(circuit)
        probs = np.array(list(counts.values())) / shots
        states = np.array([int(k, 2) for k in counts.keys()])
        expectation = np.sum(states * probs)
        ctx.save_for_backward(inputs)
        ctx.circuit = circuit
        ctx.weights = weights
        ctx.shots = shots
        ctx.backend = backend
        return torch.tensor([expectation], dtype=torch.float32)

    @staticmethod
    def backward(ctx, grad_output):
        inputs, = ctx.saved_tensors
        shift = np.pi / 2
        param_list = inputs.detach().cpu().numpy().flatten().tolist()
        grad_params = []
        for i in range(len(param_list)):
            # +shift
            param_plus = param_list.copy()
            param_plus[i] += shift
            param_bind_plus = [{ctx.weights[j]: param_plus[j] for j in range(len(ctx.weights))}]
            compiled = transpile(ctx.circuit, ctx.backend)
            qobj_plus = assemble(compiled, shots=ctx.shots, parameter_binds=param_bind_plus)
            job_plus = ctx.backend.run(qobj_plus)
            result_plus = job_plus.result()
            counts_plus = result_plus.get_counts(ctx.circuit)
            probs_plus = np.array(list(counts_plus.values())) / ctx.shots
            states_plus = np.array([int(k, 2) for k in counts_plus.keys()])
            expectation_plus = np.sum(states_plus * probs_plus)

            # -shift
            param_minus = param_list.copy()
            param_minus[i] -= shift
            param_bind_minus = [{ctx.weights[j]: param_minus[j] for j in range(len(ctx.weights))}]
            compiled = transpile(ctx.circuit, ctx.backend)
            qobj_minus = assemble(compiled, shots=ctx.shots, parameter_binds=param_bind_minus)
            job_minus = ctx.backend.run(qobj_minus)
            result_minus = job_minus.result()
            counts_minus = result_minus.get_counts(ctx.circuit)
            probs_minus = np.array(list(counts_minus.values())) / ctx.shots
            states_minus = np.array([int(k, 2) for k in counts_minus.keys()])
            expectation_minus = np.sum(states_minus * probs_minus)

            grad = 0.5 * (expectation_plus - expectation_minus)
            grad_params.append(grad)

        grad_tensor = torch.tensor(grad_params, dtype=torch.float32).view_as(inputs)
        return grad_output * grad_tensor, None, None, None, None

# ------------------------------------------------------------------
# 3.  Hybrid head – quantum
# ------------------------------------------------------------------
class _HybridQuantumHead(nn.Module):
    """Hybrid head that forwards activations through a quantum circuit."""

    def __init__(self, in_features: int, num_qubits: int = 1, depth: int = 1, shots: int = 100):
        super().__init__()
        self.linear = nn.Linear(in_features, num_qubits * depth)
        self.num_qubits = num_qubits
        self.depth = depth
        self.shots = shots
        self.backend = qiskit.Aer.get_backend("qasm_simulator")
        self.circuit, self.encoding, self.weights, self.observables = build_classifier_circuit(num_qubits, depth)

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        # Map inputs through linear layer to get circuit parameters
        params = self.linear(inputs).view(-1)
        return QuantumExpectationFunction.apply(params, self.circuit, self.weights, self.shots, self.backend)

# ------------------------------------------------------------------
# 4.  Fully‑connected layer (from FCL.py)
# ------------------------------------------------------------------
class FullyConnectedLayer(nn.Module):
    """Simple fully‑connected layer with tanh activation."""

    def __init__(self, n_features: int = 1) -> None:
        super().__init__()
        self.linear = nn.Linear(n_features, 1)

    def forward(self, thetas: torch.Tensor) -> torch.Tensor:
        values = thetas.view(-1, 1).float()
        expectation = torch.tanh(self.linear(values)).mean(dim=0)
        return expectation

# ------------------------------------------------------------------
# 5.  Feature extractor – CNN
# ------------------------------------------------------------------
class _CNNFeatureExtractor(nn.Module):
    """Convolutional backbone that can be swapped into the hybrid classifier."""

    def __init__(self, out_features: int = 120) -> None:
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, kernel_size=5, stride=2, padding=1)
        self.conv2 = nn.Conv2d(6, 15, kernel_size=3, stride=2, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=1)
        self.drop1 = nn.Dropout2d(0.2)
        self.drop2 = nn.Dropout2d(0.5)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(55815, out_features)
        self.fc2 = nn.Linear(out_features, 84)
        self.fc3 = nn.Linear(84, 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        x = self.drop1(x)
        x = F.relu(self.conv2(x))
        x = self.pool(x)
        x = self.drop1(x)
        x = self.flatten(x)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# ------------------------------------------------------------------
# 6.  Transformer components – classical
# ------------------------------------------------------------------
class MultiHeadAttentionBase(nn.Module):
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = 0.1) -> None:
        super().__init__()
        if embed_dim % num_heads!= 0:
            raise ValueError("embed_dim must be divisible by num_heads")
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor, mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        raise NotImplementedError

class MultiHeadAttentionClassical(MultiHeadAttentionBase):
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = 0.1) -> None:
        super().__init__(embed_dim, num_heads, dropout)
        self.attn = nn.MultiheadAttention(embed_dim, num_heads, dropout=dropout, batch_first=True)

    def forward(self, x: torch.Tensor, mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        attn_output, _ = self.attn(x, x, x, key_padding_mask=mask)
        return attn_output

class FeedForwardBase(nn.Module):
    def __init__(self, embed_dim: int, ffn_dim: int, dropout: float = 0.1) -> None:
        super().__init__()
        self.embed_dim = embed_dim
        self.ffn_dim = ffn_dim
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        raise NotImplementedError

class FeedForwardClassical(FeedForwardBase):
    def __init__(self, embed_dim: int, ffn_dim: int, dropout: float = 0.1) -> None:
        super().__init__(embed_dim, ffn_dim, dropout)
        self.linear1 = nn.Linear(embed_dim, ffn_dim)
        self.linear2 = nn.Linear(ffn_dim, embed_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear2(self.dropout(F.relu(self.linear1(x))))

class TransformerBlockBase(nn.Module):
    def __init__(self, embed_dim: int, num_heads: int, dropout: float = 0.1) -> None:
        super().__init__()
        self.norm1 = nn.LayerNorm(embed_dim)
        self.norm2 = nn.LayerNorm(embed_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        raise NotImplementedError

class TransformerBlockClassical(TransformerBlockBase):
    def __init__(self, embed_dim: int, num_heads: int, ffn_dim: int, dropout: float = 0.1) -> None:
        super().__init__(embed_dim, num_heads, dropout)
        self.attn = MultiHeadAttentionClassical(embed_dim, num_heads, dropout)
        self.ffn = FeedForwardClassical(embed_dim, ffn_dim, dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        attn_out = self.attn(x)
        x = self.norm1(x + self.dropout(attn_out))
        ffn_out = self.ffn(x)
        return self.norm2(x + self.dropout(ffn_out))

class PositionalEncoder(nn.Module):
    def __init__(self, embed_dim: int, max_len: int = 5000) -> None:
        super().__init__()
        position = torch.arange(0, max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, embed_dim, 2) * (-np.log(10000.0) / embed_dim))
        pe = torch.zeros(max_len, embed_dim)
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer("pe", pe.unsqueeze(0))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return x + self.pe[:, : x.size(1)]

# ------------------------------------------------------------------
# 7.  UnifiedHybridClassifier
# ------------------------------------------------------------------
class UnifiedHybridClassifier(nn.Module):
    """A versatile classifier that can operate in three modes:

    * ``mode='fc'`` – a simple fully‑connected layer (FCL).
    * ``mode='cnn'`` – a CNN backbone followed by a quantum hybrid head.
    * ``mode='transformer'`` – a transformer encoder followed by a linear head.
    """

    def __init__(
        self,
        mode: str = "fc",
        *,
        n_features: int = 1,
        out_features: int = 120,
        num_heads: int = 4,
        ffn_dim: int = 256,
        num_layers: int = 2,
        num_classes: int = 2,
        shift: float = 0.0,
    ) -> None:
        super().__init__()
        if mode not in {"fc", "cnn", "transformer"}:
            raise ValueError("mode must be one of 'fc', 'cnn', or 'transformer'")
        self.mode = mode
        self.num_classes = num_classes

        if mode == "fc":
            self.core = FullyConnectedLayer(n_features)
        elif mode == "cnn":
            self.extractor = _CNNFeatureExtractor(out_features)
            self.head = _HybridQuantumHead(out_features, num_qubits=1, depth=1)
        else:  # transformer
            self.pos_encoder = PositionalEncoder(embed_dim=num_heads * ffn_dim)
            self.transformer = nn.Sequential(
                *[
                    TransformerBlockClassical(num_heads * ffn_dim, num_heads, ffn_dim)
                    for _ in range(num_layers)
                ]
            )
            self.fc = nn.Linear(num_heads * ffn_dim, num_classes)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if self.mode == "fc":
            return self.core(x)
        elif self.mode == "cnn":
            feats = self.extractor(x)
            probs = self.head(feats)
            if self.num_classes == 2:
                return torch.cat([probs, 1 - probs], dim=-1)
            return probs
        else:  # transformer
            x = self.pos_encoder(x)
            x = self.transformer(x)
            x = x.mean(dim=1)
            logits = self.fc(x)
            if self.num_classes == 2:
                probs = torch.sigmoid(logits)
                return torch.cat([probs, 1 - probs], dim=-1)
            return logits

__all__ = [
    "FullyConnectedLayer",
    "UnifiedHybridClassifier",
    "PositionalEncoder",
    "TransformerBlockClassical",
    "FeedForwardClassical",
    "MultiHeadAttentionClassical",
]
